name: RELEASE - Build and push Docker official image to Github packages
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
      - ".github/workflows/**"
      - "**/.gitignore"
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/sympoll-vote-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Packages
        run: echo "${{ secrets.PACKAGE_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Get current date
        id: date
        run: echo "::set-output name=DATE::$(date +'%d.%m.%Y')"

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.docker/builder
          key: ${{ runner.os }}-build-${{ github.sha }}  # Cache key based on OS and commit SHA
          restore-keys: |   # Check for existing cache based on previous builds with same OS and SHA
            ${{ runner.os }}-build-

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.date.outputs.DATE }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha,key=${{ runner.os }}-build-${{ github.sha }}  # Use cached layers based on commit SHA
          cache-to: type=gha,mode=max  # Enable caching to GitHub Actions